version: "3.8"
services:
  app:
      build: .
      container_name: "php"
      ports:
        - "80:80"


  mysql_db:
    container_name: "database"
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "redhat"
      MYSQL_DATABASE: "hotel"
      MYSQL_USER: "sheeto"
      MYSQL_PASSWORD: "sheeto@123"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/hotel.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

volumes:
  db_data:

